### PR TITLE
Updating the function extract_l4_granule

### PR DESCRIPTION
**Pull request by Omkar20895**
- Replaced urlopen() with urlretrieve().
- Everything works good now in local machine.

### CODE REVIEW

**Comment by Omkar20895** [comment]
OK! Hold on. 😅

**Comment by jarifibrahim** [comment]
@Omkar20895 Can you please post a URL that I can use for testing?
I'm using `http://podaac-opendap.jpl.nasa.gov/opendap/allData/ghrsst/data/GDS2/L4/GLOB/CMC/CMC0.2deg/v2/1991/245/19910902120000-CMC-L4_GHRSST-SSTfnd-CMC0.2deg-GLOB-v02.0-fv02.0.nc` and this does not even work in browser.

**Comment by Omkar20895** [comment]
@jarifibrahim I am using the same url that you are using mate. :)

**Comment by agoodm** [comment]
@Omkar20895 @jarifibrahim @lewismc 

The 403 error we are getting is a result of attempting to download the data via opendap instead of FTP (note that the test passing python 2.7 was also a false positive, it simply downloaded a webpage containing the 403 error code). I do not know if this is was your original intent but switching to FTP should fix the problem. See my review.

**Comment by agoodm** [comment]
To be precise, we should change lines 587 in `podaac.py` to:

```python
            url = root[12][7].attrib['href']
```
and remove line 588.

**Comment by agoodm** [comment]
Yep, seems like this is the solution:
https://travis-ci.org/agoodm/podaacpy/builds/172159186

Since I went ahead and tested my own fork anyway, I will go ahead and start a new PR for this.

**Comment by Omkar20895** [comment]
@agoodm agreed 👍  Thank you very much!

**Pull request closed without merging**
