### PR TITLE
Ensure that urllib permits use within Python 2.7

### LINKED ISSUE #75: Ensure that urllib usage permits use within Python 2.7
At PO.DAAC, an important user of this library, they run Python 2.7 all of their machines.
It looks like we need to downgrade the urllib API to 2.7. I'll get on it right now.

### PR DESCRIPTION
**Pull request by jarifibrahim**
- Add python versions to .travis.yml
- Add python 2 and 3 badge to Readme
- Remove urllib and use future.moves.urllib in podaac.py and test
- Update requirements in setup.py

Fixes #75

### CODE REVIEW

**Comment by Omkar20895** [comment]
LGTM. @jarifibrahim did you try pulling @lewismc 's PR  and try to reproduce the error, cause everything worked fine in local machine with that PR. Just curious. Thanks.

**Comment by jarifibrahim** [comment]
@Omkar20895 Yes I was able to reproduce the errors. Lewis's PR uses `urllib.request.urlretrieve` to get the image file. `Urlretrieve` produces `HTTPError` if file does not exists on python 3, but it does not raise any exception on python 2.

**Comment by Omkar20895** [comment]
oh okay cool! we can merge this I guess! +1

@lewismc

**Comment by lewismc** [comment]
Thanks folks great work. This is ready to release.

**Pull request merged**
