### PR TITLE
Addressing issue#21

### PR DESCRIPTION
**Pull request by Omkar20895**
This PR addresses the [issue#21](https://github.com/lewismc/podaacpy/issues/21). All the unnecessary files are removed automatically by the test file after testing. @lewismc please take a look at it. Thanks :)

### CODE REVIEW

**Comment by lewismc** [comment]
+1 please commit

On Tuesday, June 14, 2016, Omkar <notifications@github.com> wrote:

> This PR addresses the issue#21
> <https://github.com/lewismc/podaacpy/issues/21>. All the unnecessary
> files are removed automatically by the test file after testing. Thanks :)
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/lewismc/podaacpy/pull/22
> Commit Summary
>
>    - Addressing issue#21
>
> File Changes
>
>    - *D* podaac/nose_tests_podaac/PODAAC-ASOP2-25X01_image.jpg
>    <https://github.com/lewismc/podaacpy/pull/22/files#diff-0> (0)
>    - *M* podaac/nose_tests_podaac/podaac_test.py
>    <https://github.com/lewismc/podaacpy/pull/22/files#diff-1> (6)
>
> Patch Links:
>
>    - https://github.com/lewismc/podaacpy/pull/22.patch
>    - https://github.com/lewismc/podaacpy/pull/22.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lewismc/podaacpy/pull/22>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABHJl3yXJT5LQs7YLrYPsCPbl5pd9J3Zks5qLq5qgaJpZM4I1VBU>
> .
>


-- 
*Lewis*

**Comment by Omkar20895** [comment]
@lewismc there is some issue and I am working on it right now. I will resolve it in a while. Thanks

**Comment by Omkar20895** [comment]
@lewismc can you please pull this and run it in your local image?? Please let me know if you get more than 2 errors. Thanks :)

**Comment by lewismc** [comment]
@Omkar20895 please make all pull requests against a branch. Everything always needs to work off of branches other than master OK. Thank you.

**Comment by lewismc** [comment]
When running against master this is what I get 
```
lmcgibbn@LMC-032857 /usr/local/podaacpy(22) $ nosetests  --with-coverage --cover-package=podaac.podaac,podaac.mcc
.....E.EE......
======================================================================
ERROR: podaac.nose_tests_podaac.podaac_test.test_load_image_granule
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/podaacpy/podaac/nose_tests_podaac/podaac_test.py", line 68, in test_load_image_granule
    os.remove(path)
OSError: [Errno 2] No such file or directory: '/usr/local/podaacpy/podaac/nose_tests_podaac/PODAAC-ASOP2-25X01_image.jpg'
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): podaac.jpl.nasa.gov
requests.packages.urllib3.connectionpool: DEBUG: "GET /ws/image/granule/?datasetId=PODAAC-ASOP2-25X01&shortName=ASCATA-L2-25km&granuleName=ascat_20130719_230600_metopa_35024_eps_o_250_2200_ovw.l2.nc&request=GetMap&bbox=45,0,180,90&height=300&width=200&style=EPSG:4326&srs=&service=WMS&version=1.3.0&format=image/png&layers= HTTP/1.1" 200 None
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: podaac.nose_tests_podaac.podaac_test.test_list_available_granule_search_datasetIds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/podaacpy/podaac/nose_tests_podaac/podaac_test.py", line 87, in test_list_available_granule_search_datasetIds
    data = podaac.list_available_granule_search_datasetIds()
  File "/usr/local/podaacpy/podaac/podaac.py", line 458, in list_available_granule_search_datasetIds
    json = requests.get("http://podaac.jpl.nasa.gov/dmasSolr/solr/dataset/select/?q=*:*&fl=Dataset-PersistentId,Dataset-ShortName-Full&rows=2147483647&fq=DatasetPolicy-AccessType-Full:(OPEN+OR+PREVIEW+OR+SIMULATED+OR+REMOTE)+AND+DatasetPolicy-ViewOnline:Y&wt=json").json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): podaac.jpl.nasa.gov
requests.packages.urllib3.connectionpool: DEBUG: "GET /dmasSolr/solr/dataset/select/?q=*:*&fl=Dataset-PersistentId,Dataset-ShortName-Full&rows=2147483647&fq=DatasetPolicy-AccessType-Full:(OPEN+OR+PREVIEW+OR+SIMULATED+OR+REMOTE)+AND+DatasetPolicy-ViewOnline:Y&wt=json HTTP/1.1" 503 323
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: podaac.nose_tests_podaac.podaac_test.test_list_available_granule_search_datasetShortNames
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/podaacpy/podaac/nose_tests_podaac/podaac_test.py", line 95, in test_list_available_granule_search_datasetShortNames
    data = podaac.list_available_granule_search_datasetShortNames()
  File "/usr/local/podaacpy/podaac/podaac.py", line 488, in list_available_granule_search_datasetShortNames
    json = requests.get("http://podaac.jpl.nasa.gov/dmasSolr/solr/dataset/select/?q=*:*&fl=Dataset-PersistentId,Dataset-ShortName-Full&rows=2147483647&fq=DatasetPolicy-AccessType-Full:(OPEN+OR+PREVIEW+OR+SIMULATED+OR+REMOTE)+AND+DatasetPolicy-ViewOnline:Y&wt=json").json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): podaac.jpl.nasa.gov
requests.packages.urllib3.connectionpool: DEBUG: "GET /dmasSolr/solr/dataset/select/?q=*:*&fl=Dataset-PersistentId,Dataset-ShortName-Full&rows=2147483647&fq=DatasetPolicy-AccessType-Full:(OPEN+OR+PREVIEW+OR+SIMULATED+OR+REMOTE)+AND+DatasetPolicy-ViewOnline:Y&wt=json HTTP/1.1" 503 323
--------------------- >> end captured logging << ---------------------

Name               Stmts   Miss  Cover
--------------------------------------
podaac/mcc.py         21      6    71%
podaac/podaac.py     166     57    66%
--------------------------------------
TOTAL                187     63    66%
----------------------------------------------------------------------
Ran 15 tests in 19.259s

FAILED (errors=3)
```

**Comment by lewismc** [comment]
Additionally, after I run the tests I still have the .jpg present
```
lmcgibbn@LMC-032857 /usr/local/podaacpy(22) $ git status
On branch 22
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	PODAAC-ASOP2-25X01_image.jpg
	doc.txt

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by Omkar20895** [comment]
@lewismc what is this doc.txt file in your package?? Can you please see the contents of it? Thanks.

**Comment by lewismc** [comment]
It is the result of invoking python setyp.py install, that is all

**Pull request closed without merging**
