### PR TITLE
Updating mcc.py

### PR DESCRIPTION
**Pull request by Omkar20895**
- The check_local_function was written on an assumption that all the attributes(ACDD, GDS2 and CF) parameters must be set. This is was due to lack of clarity in the API itself.
- Here http://podaac-uat.jpl.nasa.gov/mcc/about_api it was mentioned that the parameters 'MUST' be set.
- Here http://podaac-uat.jpl.nasa.gov/mcc/ beside the 'Checkers' it was mentioned 'select one or more'

### CODE REVIEW

**Comment by lewismc** [comment]
Thanks @Omkar20895 do you some tests? Also, it woukd be good to start a branch @ OCW

**Comment by Omkar20895** [comment]
I am writing the test cases for mcc.py file.

**Comment by lewismc** [comment]
brilliant thanks any idea what is going on here?
http://podaacpy.readthedocs.io/en/latest/webservices.html

**Comment by Omkar20895** [comment]
I think we need to edit it similar to the one in this link --> http://podaacpy.readthedocs.io/en/latest/mcc.html

**Comment by lewismc** [comment]
ack there seems to have been a merge which screwed it up. Can you please recommit the original file? Thanks @Omkar20895 I appreciate that.

**Comment by Omkar20895** [comment]
You want me to revert the merge and commit it again?

**Comment by lewismc** [comment]
No need. Just a commit will suffice. I am not particularly bothered about the history right now. We just need 1) documentation, 2) code and 3) to progress to writing the actual data source. 
podaacpy is the preliminary work that is being done. We have so much more to do. This is barely the beginning.

**Comment by Omkar20895** [comment]
Please pardon me. I am unable to understand what you are trying to say about the recommit thing, can please be more elaborate?

**Comment by lewismc** [comment]
Sorry.
There is no documentation at http://podaacpy.readthedocs.io/en/latest/webservices.html
There needs to be documentation at http://podaacpy.readthedocs.io/en/latest/webservices.html
Is it possible to fix that by committing the previous documentation which now seems to have been removed?

**Comment by Omkar20895** [comment]
On it!

**Comment by lewismc** [comment]
:) thank you very much.

**Comment by Omkar20895** [comment]
Done!

**Pull request merged**
