### PR TITLE
Ensure that urllib usage permits use within Python 2.7

### PR DESCRIPTION
**Pull request by lewismc**
Addresses #75

### CODE REVIEW

**Comment by lewismc** [comment]
@Omkar20895 any ideas on this one ?

https://travis-ci.org/lewismc/podaacpy/jobs/160024988

```
ERROR: test_extract_l4_granule (podaac.tests.podaac_test.test_podaac)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/lewismc/podaacpy/podaac/tests/podaac_test.py", line 160, in test_extract_l4_granule

    dataset_id, path)

  File "/home/travis/build/lewismc/podaacpy/podaac/podaac.py", line 559, in extract_l4_granule

    granule = urlretrieve(url, path)

  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/future-0.15.2-py2.7.egg/future/backports/urllib/request.py", line 225, in urlretrieve

    block = fp.read(bs)

  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/future-0.15.2-py2.7.egg/future/backports/http/client.py", line 516, in read

    return bytes(super(HTTPResponse, self).read(amt))

  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/future-0.15.2-py2.7.egg/future/backports/http/client.py", line 545, in readinto

    return self._readinto_chunked(b)

  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/future-0.15.2-py2.7.egg/future/backports/http/client.py", line 654, in _readinto_chunked

    n = self._safe_readinto(temp_mvb)

  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/future-0.15.2-py2.7.egg/future/backports/http/client.py", line 701, in _safe_readinto

    n = self.fp.readinto(mvb)

AttributeError: '_fileobject' object has no attribute 'readinto'
```

**Comment by Omkar20895** [comment]
@lewismc I have classes for the next four hours, I will get on it as soon as I am done here, as of now I don't know what is going on since I haven't looked at the code, I will pull your changes and test it in my local machine and fix it. Thanks.

**Comment by Omkar20895** [comment]
So, I pulled this request into my local machine and ran nosetests-3.4 everything worked fine, all tests passed OK. I tried to find the error online but ended up with nothing.

**Comment by lewismc** [comment]
@Omkar20895 the build is working better now however the Python2.7 build is still giving an issue
https://travis-ci.org/lewismc/podaacpy/jobs/160345993
```
======================================================================

FAIL: test_granule_preview (podaac.tests.podaac_test.test_podaac)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/lewismc/podaacpy/podaac/tests/podaac_test.py", line 141, in test_granule_preview

    self.podaac.granule_preview, dataset_id='PODAAC-ASOP2-25X01', image_variable='hello')

AssertionError: Exception not raised

-------------------- >> begin captured stdout << ---------------------

http://podaac-tools.jpl.nasa.gov/l2ss-services/l2ss/preview/PODAAC-ASOP2-25X01/2016/198/ascat_20160716_092100_metopa_50544_eps_o_250_2401_ovw.l2.nc/wind_speed.png

http://podaac-tools.jpl.nasa.gov/l2ss-services/l2ss/preview/PODAAC-ASOP2-25X01/2016/198/ascat_20160716_092100_metopa_50544_eps_o_250_2401_ovw.l2.nc/hello.png

--------------------- >> end captured stdout << ----------------------

-------------------- >> begin captured logging << --------------------

requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): podaac.jpl.nasa.gov

requests.packages.urllib3.connectionpool: DEBUG: "GET /ws/search/granule/?datasetId=PODAAC-ASOP2-25X01&bbox=-180,-90,180,90&sortBy=timeAsc&itemsPerPage=7&format=atom&pretty=True HTTP/1.1" 200 None

requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): podaac.jpl.nasa.gov

requests.packages.urllib3.connectionpool: DEBUG: "GET /ws/search/granule/?datasetId=PODAAC-ASOP2-25X01&bbox=-180,-90,180,90&sortBy=timeAsc&itemsPerPage=7&format=atom&pretty=True HTTP/1.1" 200 None

--------------------- >> end captured logging << ---------------------
```

**Comment by Omkar20895** [comment]
@lewismc I am on it.

**Comment by Omkar20895** [comment]
@lewismc can you please add these lines in your code and add a commit? I think this should solve the issue.

[Suggested Changes.zip](https://github.com/lewismc/podaacpy/files/476849/Suggested.Changes.zip)

**Comment by lewismc** [comment]
This is becoming a PITA. We are very close to getting it working properly.

**Comment by Omkar20895** [comment]
@lewismc I think you missed a change in the patch that I have sent to you, it's in the podaac_test file where I have replaced 

> Exception

with 

> HTTPError

the line is crucial to this issue, please change that line and I am guess that would solve our issue here. thank you very much.

**Comment by lewismc** [comment]
We will see. Thanks @Omkar20895

**Comment by lewismc** [comment]
... bugger

**Comment by Omkar20895** [comment]
What could it possibly be!

**Comment by lewismc** [comment]
has anyone got a clue what is going on.

**Comment by jarifibrahim** [comment]
Please take a look at https://github.com/lewismc/podaacpy/pull/77

This branch was messy so I've sent a new PR

**Comment by lewismc** [comment]
Closing as this was addressed in #77

**Pull request closed without merging**
